### ISSUE TITLE
node js / express

### ISSUE THREAD

**Issue by visheshtungarev** [SSENSE/node-sscheduler#8]
how can i use it in my node js app 
its gives me error "var myScheduler = new Scheduler();
                  ^

TypeError: Scheduler is not a constructor
    at Object.<anonymous> (E:\Hatook\TheDoctorApp\app.js:9:19)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3"

**Comment by quinnlangille** [comment]
hey @visheshtungarev, sorry for the late reply. Not sure if you were still having the issue or still working on this, but if you are mind sharing how you're importing `Scheduler`?
